### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by db4k** [ogkalu2/comic-translate#224]
Ultralytics 8.3.40 🚀 Python-3.11.9 torch-2.6.0+cpu
An error occurred:
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

Traceback:
Traceback (most recent call last):
  File "D:\comic-translate\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comic-translate\pipeline.py", line 57, in detect_blocks
    blk_list = self.block_detector_cache.detect(image)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comic-translate\modules\detection.py", line 22, in detect
    bble_detec_result = self.bubble_detection(img, device=self.device, imgsz=size, conf=0.1, verbose=False)[0]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comic-translate\.venv\Lib\site-packages\ultralytics\engine\model.py", line 179, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comic-translate\.venv\Lib\site-packages\ultralytics\engine\model.py", line 550, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "D:\comic-translate\.venv\Lib\site-packages\ultralytics\engine\predictor.py", line 310, in setup_model
    device=select_device(self.args.device, verbose=verbose),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comic-translate\.venv\Lib\site-packages\ultralytics\utils\torch_utils.py", line 192, in select_device
    raise ValueError(
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

**Comment by ogkalu2** [comment]
Hey. Try updating and see if it works now after doing:

uv remove torch torchvision paddlepaddle
uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121
uv pip install paddlepaddle-gpu
